#! /usr/bin/bash 
./stow.sh i3
./stow.sh zsh
./stow.sh compton
./stow.sh termite
./stow.sh nvim
./stow.sh fontconfig
./stow.sh autostart
./stow.sh git
./stow.sh wpgtk
./stow.sh rofi
./stow.sh polybar
./stow.sh i3-env
./stow.sh autorandr
./stow.sh splatmoji
./stow.sh profile
./stow.sh ctags
./stow.sh ranger
./stow.sh status-one-liner
./stow.sh ignore
./stow.sh taskwarrior
./stow.sh kitty
./stow.sh tig
./stow.sh slop
./stow.sh spicetify
