#! /usr/bin/bash 
./stow.sh i3
./stow.sh zsh
./stow.sh compton
./stow.sh termite
./stow.sh vim
./stow.sh fontconfig
./stow.sh autostart
./stow.sh git
./stow.sh wpgtk
./stow.sh rofi
./stow.sh polybar
./stow.sh i3-env
./stow.sh autorandr
